### PR TITLE
KMCNG-37 Login redesign - Add signup button color

### PR DESCRIPTION
**Pull request by diamond-darrell**
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kaltura-ng-mc-theme/1)

### CODE REVIEW

**Comment by kaltura-hooks** [comment]
Hi @diamond-darrell,
Thank you for contributing this pull request!
Please sign the Kaltura CLA so we can review and merge your contribution.
Learn more at http://bit.ly/KalturaContrib

**Comment by esakal** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng-mc-theme/1#-:-Kr69e_mqnRPCFMiO9rx:bnfp4nl)*

**Comment by amirch1** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[themes/default/scss/_variables.scss, line 41 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng-mc-theme/1#-Kr6AkAUNQkFqBOvQb83:-Kr6AkAVsXgxaueCc3th:bxjx15b) ([raw file](https://github.com/kaltura/kaltura-ng-mc-theme/blob/455117045744565d02fbf2671db38be373c81db9/themes/default/scss/_variables.scss#L41)):*
> $kLoginSignUpBtn
Why do we need this? The login button is a regular button in terms of colors

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng-mc-theme/1)*

**Comment by diamond-darrell** [comment]
*[themes/default/scss/_variables.scss, line 41 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng-mc-theme/1#-Kr6AkAUNQkFqBOvQb83:-Kr6GoAxVTMoeNz2IuZV:b-sa9slu) ([raw file](https://github.com/kaltura/kaltura-ng-mc-theme/blob/455117045744565d02fbf2671db38be373c81db9/themes/default/scss/_variables.scss#L41)):*
<details><summary><i>Previously, amirch1 (Amir Chervinsky) wrote…</i></summary><blockquote>

> $kLoginSignUpBtn
Why do we need this? The login button is a regular button in terms of colors
</blockquote></details>

You right, I'll remove it from theme repo

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng-mc-theme/1)*

**Comment by diamond-darrell** [comment]
*[themes/default/scss/_variables.scss, line 41 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng-mc-theme/1#-Kr6AkAUNQkFqBOvQb83:-Kr6H2uRXpeOKFyMhZZa:b32w0x) ([raw file](https://github.com/kaltura/kaltura-ng-mc-theme/blob/455117045744565d02fbf2671db38be373c81db9/themes/default/scss/_variables.scss#L41)):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

You right, I'll remove it from theme repo
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng-mc-theme/1)*

**Comment by diamond-darrell** [comment]
*[themes/default/scss/_variables.scss, line 41 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng-mc-theme/1#-Kr6AkAUNQkFqBOvQb83:-Kr6HqF0XTH1Erco1FZe:b-weuaj1) ([raw file](https://github.com/kaltura/kaltura-ng-mc-theme/blob/455117045744565d02fbf2671db38be373c81db9/themes/default/scss/_variables.scss#L41)):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

OK
</blockquote></details>

So, I think you can just close PR without merge, I did changes in kmc-ng repo for that color

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng-mc-theme/1)*

**Comment by esakal** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[themes/default/scss/_variables.scss, line 41 at r1](https://reviewable.io:443/reviews/kaltura/kaltura-ng-mc-theme/1#-Kr6AkAUNQkFqBOvQb83:-Kr6In3bgoWJyKGpYC22:bbcr0cf) ([raw file](https://github.com/kaltura/kaltura-ng-mc-theme/blob/455117045744565d02fbf2671db38be373c81db9/themes/default/scss/_variables.scss#L41)):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

So, I think you can just close PR without merge, I did changes in kmc-ng repo for that color
</blockquote></details>

sure, I will close the PR and delete the branch

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kaltura-ng-mc-theme/1)*

**Pull request closed without merging**
